name = "AlgebraicVision"
uuid = "71182054-b433-4cee-bfde-f91a92577372"
authors = ["Viktor Korotynskiy <korotynskiy.viktor@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.8"
